#!/bin/bash

echo "🚀 Deploying Next.js Website to Vercel"
echo "========================================"

# Step 1: Initialize git if not already
if [ ! -d ".git" ]; then
    echo "📦 Initializing git repository..."
    git init
    git add .
    git commit -m "Initial Next.js version of personal website"
else
    echo "📦 Git repository already initialized"
fi

echo ""
echo "📋 Next Steps:"
echo "=============="
echo ""
echo "1. Create GitHub repository:"
echo "   Go to: https://github.com/new"
echo "   Name: jixiong-next (or jixiong-website)"
echo "   DO NOT initialize with README, .gitignore, or license"
echo ""
echo "2. After creating repository, run:"
echo "   git remote add origin https://github.com/arthanusamn/jixiong-next.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy to Vercel:"
echo "   Go to: https://vercel.com/new"
echo "   Import 'arthanusamn/jixiong-next'"
echo "   Click 'Deploy'"
echo ""
echo "4. Your site will be at:"
echo "   https://jixiong-next.vercel.app"
echo ""
echo "🎯 What's being deployed:"
echo "========================"
echo "✅ Next.js 14 with App Router"
echo "✅ Tailwind CSS v4 with custom design"
echo "✅ Responsive navigation (mobile/desktop)"
echo "✅ Dashboard with all sections"
echo "✅ Portfolio, Learning, Projects, Goals pages"
echo "✅ System status monitoring"
echo "✅ Dark theme with gradients"
echo ""
echo "📊 Current project status:"
echo "========================="
echo "• Next.js version: $(grep '"next"' package.json | cut -d'"' -f4)"
echo "• React version: $(grep '"react"' package.json | cut -d'"' -f4)"
echo "• Tailwind CSS: v4"
echo "• TypeScript: Enabled"
echo "• Pages: 7 (Home, Portfolio, Learning, Projects, Goals, Rocky, Actions)"
echo ""
echo "🔗 After deployment:"
echo "==================="
echo "1. Test: https://jixiong-next.vercel.app"
echo "2. Compare with: https://jixiong.vercel.app (current HTML version)"
echo "3. Set up auto-deploy on git push"
echo "4. Consider custom domain"
echo ""
echo "🎵 Ready to deploy! Follow steps 1-3 above."